#!/usr/bin/env python3
"""Refresh Kalshi bid/ask/last for the WC2026 fair-probabilities dashboard.

Mirrors the MLB playoff-odds pipeline's Kalshi approach (server-side fetch,
no auth, prefer the populated `*_dollars` quote fields). Fetches every World
Cup market for the 6 dashboard markets, maps each Kalshi contract to our
canonical team name, and splices a `const KALSHI = {...}` block into
wc2026-fair-probabilities.html between the // <<KALSHI>> markers.

Run it whenever you want fresh quotes (this is the equivalent of the MLB
page's cron re-render):

    python3 wc2026_kalshi_refresh.py
"""
from __future__ import annotations
import json, time, sys, os, re
import requests  # same HTTP client as the MLB pipeline (bundles CA certs)

BASE = "https://api.elections.kalshi.com/trade-api/v2"
UA = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) wc2026-dashboard"
HTML = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                    "index.html")

# app-market -> (series_ticker, round_segment_filter or None)
# For KXWCROUND the round lives in the ticker's 2nd segment (e.g. 26FINAL).
SERIES = {
    "outright": ("KXMENWORLDCUP", None),
    "final":    ("KXWCROUND", "26FINAL"),
    "semi":     ("KXWCROUND", "26SEMI"),
    "quarter":  ("KXWCROUND", "26QUAR"),
    "wingroup": ("KXWCGROUPWIN", None),
    "advance":  ("KXWCGROUPQUAL", None),
}

# Kalshi yes_sub_title -> our canonical TEAM_NAMES
KALSHI2OURS = {
    "USA": "United States", "Turkey": "Türkiye", "Turkiye": "Türkiye",
    "Ivory Coast": "Côte d'Ivoire", "Cape Verde": "Cabo Verde",
    "Curacao": "Curaçao", "Congo DR": "DR Congo",
    "Korea Republic": "South Korea", "IR Iran": "Iran",
}

def canon(name: str) -> str:
    return KALSHI2OURS.get(name, name)

def _get(path: str, params: dict) -> dict:
    backoff = 1.0
    for _ in range(6):
        r = requests.get(f"{BASE}{path}", params=params,
                         headers={"User-Agent": UA, "Accept": "application/json"},
                         timeout=30)
        if r.status_code == 429:
            time.sleep(backoff); backoff *= 2; continue
        r.raise_for_status()
        return json.loads(r.text, strict=False)
    raise RuntimeError(f"giving up on {path}")

def fetch_series(series: str) -> list[dict]:
    """All open markets for a series, paginated."""
    out, cursor = [], ""
    for _ in range(8):
        params = {"series_ticker": series, "limit": 500, "status": "open"}
        if cursor:
            params["cursor"] = cursor
        d = _get("/markets", params)
        out.extend(d.get("markets") or [])
        cursor = d.get("cursor") or ""
        if not cursor:
            break
        time.sleep(0.4)
    return out

def to_f(x):
    try:
        return None if x in (None, "") else float(x)
    except (TypeError, ValueError):
        return None

def quote(m: dict) -> dict:
    # Prefer the populated *_dollars decimals; fall back to integer cents/100.
    def pick(dollars_key, int_key):
        v = to_f(m.get(dollars_key))
        if v is not None:
            return v
        iv = m.get(int_key)
        return None if iv in (None, "") else iv / 100.0
    return {
        "bid":  pick("yes_bid_dollars", "yes_bid"),
        "ask":  pick("yes_ask_dollars", "yes_ask"),
        "last": pick("last_price_dollars", "last_price"),
        "ticker": m.get("ticker"),
    }

def build() -> dict:
    data = {}
    for mkt, (series, seg) in SERIES.items():
        markets = fetch_series(series)
        bucket = {}
        for m in markets:
            if seg is not None:
                parts = (m.get("ticker") or "").split("-")
                if len(parts) < 2 or parts[1] != seg:
                    continue
            team = canon(m.get("yes_sub_title") or m.get("subtitle") or "")
            if not team:
                continue
            bucket[team] = quote(m)
        data[mkt] = bucket
        print(f"  {mkt:9} {len(bucket)} contracts (series {series}{'/'+seg if seg else ''})")
        time.sleep(0.4)
    return data

def js_number(x) -> str:
    if x is None:
        return "null"
    return ("%.4f" % x).rstrip("0").rstrip(".") or "0"

def emit(data: dict) -> str:
    order = ["outright", "final", "semi", "quarter", "wingroup", "advance"]
    lines = ["  // <<KALSHI>>  generated by wc2026_kalshi_refresh.py — do not hand-edit",
             "  const KALSHI = {"]
    for mkt in order:
        lines.append(f"    {mkt}: {{")
        for team in sorted(data.get(mkt, {})):
            q = data[mkt][team]
            lines.append(
                f'      {(chr(34)+team+chr(34)+":"):28} '
                f'{{ bid: {js_number(q["bid"])}, ask: {js_number(q["ask"])}, '
                f'last: {js_number(q["last"])}, ticker: "{q["ticker"]}" }},')
        lines.append("    },")
    lines.append("  };")
    lines.append("  // <</KALSHI>>")
    return "\n".join(lines)

def splice(block: str):
    html = open(HTML, encoding="utf-8").read()
    start = html.find("  // <<KALSHI>>")
    end = html.find("// <</KALSHI>>")
    if start != -1 and end != -1:
        end = html.find("\n", end) + 1
        html = html[:start] + block + "\n" + html[end:]
    else:
        # First run: insert just before buildTeams().
        anchor = "  // Build the 48-team array for a market"
        i = html.index(anchor)
        html = html[:i] + block + "\n\n" + html[i:]
    open(HTML, "w", encoding="utf-8").write(html)

if __name__ == "__main__":
    print("Fetching Kalshi WC2026 markets...")
    data = build()
    splice(emit(data))
    stamp = time.strftime("%Y-%m-%d %H:%M:%S")
    print(f"Injected KALSHI block into {os.path.basename(HTML)} at {stamp}")
